### ISSUE TITLE
Feature Request: Add a cool-down option

### ISSUE THREAD

**Issue by Ellendyra** [Crazy-Crew/Vouchers#13]
I would like to use this plugin to give out vouchers for temporary permissions (Handed out via luckperms) 

I would appreciate it if there was an option to have a cool-down period so the player couldn't use the same voucher again for say 20 minutes, or 1 hour. That way they can't waste the vouchers by doing them again too early.

**Comment by RyderBelserion** [comment]
Added to tracker.
