### ISSUE TITLE
[Bug Report] Critical: NBT-API Broken on 1.16.2

### ISSUE THREAD

**Issue by viveleroi** [Crazy-Crew/Vouchers#15]
**Describe the bug**
No vouchers work. Given command throws console error.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.2
 - Plugin Version: Vouchers[v1.8.15]

*Do **NOT** say Latest use `/version vouchers` in the console.

**Pastebin any errors in console**
https://gist.github.com/viveleroi/7cc05e5bc8efbf1eb199ce46a0ee205b

**Issue**
NBT-API error prevents plugin from working.

**Screenshots**
N/A

**Comment by ConfuseN** [comment]
Having the same issue

**Comment by RyderBelserion** [comment]
Fixed.
