### ISSUE TITLE
[Suggestion] Add filled map ID possible as voucher item

### ISSUE THREAD

**Issue by Davisiiiik** [Crazy-Crew/Vouchers#17]
Hello!
Could you add feature to make a voucher from filled map with specific ID?
For example I have a lottery ticket map art stored as map_100.dat (Item_name: minecraft:filled_map{map:100}) and I would like to have it as a voucher, so when a player is given it, he can see it in his own hand like this:

![voucher_map](https://user-images.githubusercontent.com/79375965/109230748-a676d380-77c5-11eb-85a1-bfa09978ab1e.png)

**Comment by RyderBelserion** [comment]
Added to tracker.
