### ISSUE TITLE
[Bug Report] The secondary hand places the voucher

### ISSUE THREAD

**Issue by hintikulus** [Crazy-Crew/Vouchers#20]
**Describe the bug**
When the voucher is set to a placeable item, and the player inserts the voucher into the secondary hand and attempts to redeem it when looking at the ground, for example, the item is placed and no actions of the voucher are performed.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.5 (tried on Spigot-2991 and Paper-742)
 - Plugin Version: 1.8.16-RELEASE

**Comment by RyderBelserion** [comment]
Added to bug tracker.
