### ISSUE TITLE
[Suggestion] Dupe/copy protection on vouchers

### ISSUE THREAD

**Issue by chrismwiggs** [Crazy-Crew/Vouchers#21]
I know lots of duping glitches are patched quite fast by Spigot and Paper, but people are creative and seem to find ways!

What my suggestion is, is to have some sort of basic copy _mitigation_ (vs protection). I am imagining a system where every time a voucher is given as an item, it is given a UID in the NBT and an entry for the UID is added to the database. 

When a voucher is clicked/redeemed, the UID would be looked up and confirmed that it is marked unredeemed. If a copy of a voucher _was_ made, and the original was redeemed, the copy would lookup the already redeemed UID and return an error to the user/deny the redeem. 

Not bullet proof of course, but would ease my mind knowing the lengths some people go to try and break things!

**Comment by RyderBelserion** [comment]
Added to project tracker.
