### ISSUE TITLE
[Bug Report] NPT-API errors on 1.17

### ISSUE THREAD

**Issue by viveleroi** [Crazy-Crew/Vouchers#22]
**Describe the bug**
NBT-API errors with any voucher command use on 1.17.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.17
 - Plugin Version: v1.8.19

**Pastebin any errors in console**
https://paste.gg/p/anonymous/57918e305a594600b8ff041c34c4a42a

**Comment by RyderBelserion** [comment]
You need to join our discord and verify that you own the plugin then you will have access to the beta version of the plugin which I've updated to work on 1.17. 

https://discord.gg/Wj2cEHUsqP

**Comment by RyderBelserion** [comment]
Fixed.
