### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by matthewtrains** [Crazy-Crew/Vouchers#28]
**Describe the bug**
Player has the permission to use vouchers but it shows up in chat that i do not have permission

**Versions (please complete the following information):**
- minecraft 1.19

*Do **NOT** say Latest use `/version vouchers` in the console.

**Issue**
I given my alt account permission to use /voucher redeem but every time i go to do so it says contact the admin
**Screenshots**

**Comment by RyderBelserion** [comment]
The permissions is voucher.redeem, Make sure they have the right player group.

**Comment by matthewtrains** [comment]
![Bug](https://user-images.githubusercontent.com/20475752/178610906-7d3596e9-1a2d-41ec-9488-7054e1417bcf.png)

**Comment by matthewtrains** [comment]
ive used that permission and it still doesent work, i also made sure the command can be used in my tab complete filter

**Comment by matthewtrains** [comment]
as of testing i have my alt, speccifcly have the perm outside of the default group

**Comment by RyderBelserion** [comment]
![image](https://user-images.githubusercontent.com/52214219/178613619-d5849f77-e838-45a5-8ee2-4dc5e3de3997.png)

Join the discord @ https://discord.badbones69.com
