### ISSUE TITLE
Error while using some of symbols

### ISSUE THREAD

**Issue by Silvobi** [Crazy-Crew/Vouchers#3]
When you change in locale something that will contain symbols like [ą,ę,ć,ó] it will instead give strange question mark symbol in GUI

**Comment by RyderBelserion** [comment]
Make sure you edit your startup flags like below.

![image](https://user-images.githubusercontent.com/52214219/183540252-bcabe084-8847-4602-88c1-bd68b0f07770.png)

![image](https://user-images.githubusercontent.com/52214219/183540311-6f97f424-f7ab-44db-9dcb-4dd8611764db.png)

**Comment by Silvobi** [comment]
won't this break other plugins?

**Comment by RyderBelserion** [comment]
No
