### ISSUE TITLE
[Bug Report] - Voucher's can be used to craft things...

### ISSUE THREAD

**Issue by ClickErrorxD** [Crazy-Crew/Vouchers#31]
**Describe the bug**
Voucher's can be used to craft items assuming the voucher item type is in vanilla crafting recipe.

**Versions (please complete the following information):**
Minecraft Server Version: Paper Spigot 1.18.2
Plugin Version: Vouchers[v1.9.1].jar

**Pastebin any errors in console**
There is 0 console errors associated with this bug.

**Issue**
Voucher's can be used to craft items assuming the voucher item type is in vanilla crafting recipe.

**Screenshots**
Here is a video for clear evidence of the issue: https://youtu.be/ZMlUVEvV46g

**Comment by RyderBelserion** [comment]
Are you in the Discord? If so verify....

**Comment by ClickErrorxD** [comment]
> Are you in the Discord? If so verify.... so I can give you a test build.

![image](https://user-images.githubusercontent.com/87890013/179662426-ce4fd343-e39b-4f95-9497-5b7e88a3c8c7.png)

**Comment by RyderBelserion** [comment]
Solved and will be posting build on Spigot.
