### ISSUE TITLE
Vouchers Issue

### ISSUE THREAD

**Issue by DebuffPvP** [Crazy-Crew/Vouchers#32]
**Describe the bug**
Console

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.8.8
 - Plugin Version: 1.8.7 from spigot

*Do **NOT** say Latest use `/version vouchers` in the console.
When i did this command in console it shows 1.8.6 though

**Pastebin any errors in console**
Link: https://pastebin.com/88HPDRUU

**Comment by RyderBelserion** [comment]
That is unrelated to Vouchers. Check the EssentialsX faq.
