### ISSUE TITLE
Voucher Issue [Put the wrong link on the last ticket]

### ISSUE THREAD

**Issue by DebuffPvP** [Crazy-Crew/Vouchers#33]
Describe the bug
Console

Versions (please complete the following information):

Minecraft Server Version: 1.8.8
Plugin Version: 1.8.7 from spigot
*Do NOT say Latest use /version vouchers in the console.
When i did this command in console it shows 1.8.6 though

Pastebin any errors in console
Link: https://www.toptal.com/developers/hastebin/vumafitido.rb

Sorry about the one i made previously i was multi tasking and reporting issues for other plugins as well and mixed up that link with this right one

**Comment by RyderBelserion** [comment]
Update to v1.9.8
