### ISSUE TITLE
Blacklist Permissions

### ISSUE THREAD

**Issue by JohnnyPixelz** [Crazy-Crew/Vouchers#7]
Blacklist permissions do not prevent the player from reusing a voucher. If you cannot recreate, I will reach you.

Voucher version: 1.7.8
Server version: PaperSpigot 1.8.8

**Comment by badbones69** [comment]
Can you pastebin the config.yml for me?

**Comment by JohnnyPixelz** [comment]
There you go. https://pastebin.com/T3RpeDVi

**Comment by badbones69** [comment]
I am having no issues. You made sure your not an op when you open it right?

**Comment by JohnnyPixelz** [comment]
I tried both with op and not, and made sure I was in the default group.

**Comment by badbones69** [comment]
Hmmm, the only thing I can do is have you join my discord so I can send you a debug version to help show me the issue.

**Comment by RyderBelserion** [comment]
Fixed
